---
# /roles/install_docker/tasks/main.yaml
# this role installs the required packages for docker
# according to the docker documentation
# https://docs.docker.com/engine/install/ubuntu/ 

# 1 remove all conflicting packages
- name: Remove all conflicting packages
  ansible.builtin.shell: |
    for pkg in \
      docker.io \
      docker-doc \
      docker-compose \
      docker-compose-v2 \
      podman-docker \
      containerd \
      runc; do
      sudo apt-get remove -y $pkg
    done
  args:
    executable: /bin/bash


# 2 Add Docker's official GPG key
- name: Add Docker's official GPG key
  ansible.builtin.shell: |
    apt-get update
    apt-get install -y ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL \
      https://download.docker.com/linux/ubuntu/gpg \
      -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    executable: /bin/bash



# 3 Set up the Docker repository
- name: Set up the Docker repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) \
      signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
  args:
    executable: /bin/bash


# 4 Install Docker
- name: Install Docker
  ansible.builtin.shell: |
    apt-get update
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io \
      docker-buildx-plugin \
      docker-compose-plugin
  args:
    executable: /bin/bash

# 5 Start and enable Docker service
- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

# 6 Create the /home/{{ ansible_user }}/docker directory
- name: create /home/{{ ansible_user }}/docker directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/docker
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
    recurse: true