---
# /roles/delete_vm/tasks/main.yaml
# This playbook Reverts VMs to start snapshot

- name: Reverts VMs to snapshot Start
  hosts: nuc_zotac_group
  become: true
  gather_facts: true
  strategy: free
  
  tasks:
    - name: Check if VMs exist and revert to snapshot 'Start'
      ansible.builtin.shell: |
        qm status {{ item.vm_id }} && qm rollback {{ item.vm_id }} start && qm start {{ item.vm_id }} || true
      loop: "{{ vm_list }}"
      loop_control:
        label: "Reverting {{ item.vm_name }}"
      args:
        executable: /bin/bash