
---
# playbook:2.yaml
# this playbook changes hostname, installs nfs share, kubernetes, 
# cri-dockerd socket, initializes kubernetes, joins workers and 
# installs helm on master node

- name: Playbook 4 - Install Kubernetes
  hosts: all_vm
  become: true
  gather_facts: true
  strategy: free
  
  pre_tasks:

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        state: latest
      ignore_errors: True
    
    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: full
        state: latest
      ignore_errors: True

  roles:
    - 4.2_configure_ssh
    - 5_install_nfs
    - 6_install_docker


- name: TEST SNAPSHOT
  hosts: nuc_zotac_group
  become: true
  gather_facts: true

  tasks:
      - name: Create snapshots
        ansible.builtin.shell: |
          qm status {{ item.vm_id }} && qm snapshot {{ item.vm_id }} start
        loop: "{{ vm_list }}"
        loop_control:
          label: "Snapshotting VM {{ item.vm_name }}"
        args:
          executable: /bin/bash

- name: Playbook 4.3 - Install Kubernetes
  hosts: all_vm
  become: true
  gather_facts: true
  strategy: free
  roles:
    - 7_install_kubernetes
    - 8_install_cri-dockerd



- name: Playbook 4.5 - Install Kubernetes
  hosts: all_vm
  become: true
  gather_facts: true

  roles:
    - 9_initialize_kubernetes
    - 10_install_helm
    - 11_install_metallb
    - 12_install_rook
    - 20_copy_files


